# Generated by Django 5.0.6 on 2024-07-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('agendado', 'Agendado'), ('finalizado', 'Finalizado')], default='pendente', max_length=20),
        ),
    ]
